/**
 * Fixed, known-good retention structure for true crime narration scripts.
 * These are applied directly in every script's section prompts rather than
 * being regenerated by the model each time — they're proven techniques,
 * not something that needs to be reinvented per script. If/when a
 * per-creator adaptive learning loop is built later, this list becomes the
 * default baseline that gets refined by performance data, not replaced by it.
 */
export const TRUE_CRIME_RETENTION_PRINCIPLES: string[] = [
  "Open cold within the first 15-30 seconds — no slow preamble, no channel intro, no scene-setting before the hook lands.",
  "Introduce a new detail, twist, or question at least once every 60-90 seconds of narration (roughly every 150-220 words) to prevent viewer drop-off.",
  "Tease the resolution or key reveal early, but withhold the full answer until late in the script — hold back at least one significant reveal for the final third.",
  "Never front-load case facts in a single block — spread specific details (names, dates, evidence) across the script as the story naturally reaches them, not all at once.",
  "End every section other than the final one on an open question, unresolved detail, or rising tension — a cliffhanger that pulls the viewer into the next section rather than a settled, resolved beat.",
  "For long-form scripts, treat the middle sections as the highest drop-off risk — deploy pattern interrupts and mini-reveals more deliberately through the middle third, not just at the open and close.",
  "Vary sentence rhythm and pacing — short, punchy sentences at tension points; longer, descriptive sentences during scene-setting — to keep the narration audibly dynamic rather than monotone.",
];

export const LONG_SCRIPT_WORD_THRESHOLD = 10000;